### ISSUE TITLE
Looks great!

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [AltoRetrato/gditools3#1]
Your GUI looks and runs just like a Windows program.  If I didn't know better, I would not think it was written in Python.  Nice job of working with what you've got and making the most of it.

Soon you'll be able to run it on Qt if you want.  The table handling should be a lot better in Qt.

**Comment by AltoRetrato** [comment]
Thanks for you hard work on PySimpleGUI! I wouldn't write a GUI for this if it wasn't for it.

**Comment by MikeTheWatchGuy** [comment]
You're quite welcome.... I wrote this package for myself at first, but then saw how amazing it was I had to release it to the community.  I got lucky is all.  I happened to stumble onto a way to make GUIs really easy using a combination of Python features.   Anyone could have done this, but for some weird reason, no one has.

I got my first WxPython window up today... it's crude, primitive, but it's real PySimpleGUI code... 3 elements, the window and read calls / event loop are all operational.  All in an afternoon.  It's super simple to port this thing.  I can't wait to get Qt done, then crank out WxPython and finally hit Kivy.

Thanks for the encouragement.  It's helpful 👍 
![snag-0264](https://user-images.githubusercontent.com/13696193/48653289-39fbb000-e9d2-11e8-9bdb-60f1e014834b.jpg)

**Comment by AltoRetrato** [comment]
Nice! One major advantage of wxPython over Qt must be the binary size of a script frozen by pyinstaller. OTOH, it looks a lot like tkinter. Is there any advantage of using wxPython over tkinter?

**Comment by MikeTheWatchGuy** [comment]
LOTS of people continue to download Wx.  Part of the people I get are experienced users of tkinter or Qt that want to prototype or quickly throw together a simple GUI for a tool.  They admit it's a LOT easier using PySimpleGUI.  

Wx does have some features that are easier than the others, like system tray application like I've been wanting.  

I keep checking for the episode to post on a Podcast, Python Bytes.  They're doing a story on PySimpleGUI :-)

I'm going to do all of the GUI frameworks that have a decent audience.  Kivy is up after Wx.  It's not going to be pleasant, but it will be popular if I pull it off.

It would be a miracle if one version of PySimpleGUI program could run on 5 platforms by changing only the import statement, or by setting a variable in your code prior to the import.

**Comment by AltoRetrato** [comment]
> It would be a miracle if one version of PySimpleGUI program could run on 5 platforms by changing only the import statement, or by setting a variable in your code prior to the import.

Which platforms? Windows, Linux, Mac, Android & iOS? Unless it's something really simple, you'd need a responsive interface. It's not impossible (there are plenty of websites like that), but also not so easy to build.

**Comment by MikeTheWatchGuy** [comment]
I meant GUI Frameworks.  Each Framework would bring along with it multiple platforms.  tkinter runs on everything but mobile as does Qt (Win, Linux, Mac).  Qt claims they are going mobile.  For now it's going to have to be tkinter.

Just heard about PyBee too.  Another example where I can wrap a GUI capability.  All I'm doing is offering a simplified SDK to these platforms' widgets. PyBee looks interesting in terms of simply getting code to run on the platform

Toga is another one that would be good to do.  I want to leverage the difficult work these projects are doing by grabbing them and re-purposing them to fit my SDK.  

I think there's something pretty magical about the PySimpleGUI SDK itself.  There should be an 'alternate' set of interfaces available for all of these GUIs that resemble PySimpleGUI.  To be honest, I'm baffled as to why no one has made a GUI interface like this one.  I just wish mine was a tad more stable with multiple window situations.

They key seems to be a "classless" or procedural interface.   Despite the Elements being objects, there is no use of classes from the user's point of view, although I've seen some OO code using PySimpleGUI and I find it very difficult to read.
